### ISSUE TITLE
await client.disconnectSFTP() never terminates

### ISSUE THREAD

**Issue by ahoelzemann** [jda258/flutter_ssh2#2]
Hi Josh,

thanks again for the nice work and for updating this very useful but kind of forgotten package. 

I'm able to upload data with the newest version with a real iPhone X device as well as with a Nexus 5 (Android 30), however, after I finished the upload I'm not able to disconnect from the server, since the function await client.disconnectSFTP() never finishes. This happens with both operating systems.

I hope you will find the time to look into that problem. 

best regards,
Alex

**Comment by jda258** [comment]
Hi Alex,

It's my pleasure to give back to the community when this package has been so useful for me as well!

I remember running into this issue pre-fork and simply used client.disconnect() instead. I've looked into this issue, but don't see anything obvious in the code.

This is in ssh2.dart:
``` dart
  Future disconnectSFTP() async {
    uploadCallback = null;
    downloadCallback = null;
    await _channel.invokeMethod('disconnectSFTP', {
      "id": id,
    });
  }
```

And the associated code for Android and iOS:
SshPlugin.java:
``` java
  private void disconnect(final HashMap args) {
    this.closeShell(args);
    this.disconnectSFTP(args);

    SSHClient client = clientPool.get(args.get("id"));
    if (client == null)
      return;
    client._session.disconnect();
  }
```
SshPlugin.m:
``` objc
- (void) disconnectSFTP:(nonnull NSString*)key {
  SSHClient* client = [self clientForKey:key];
  if (client && client._sftpSession) {
    [client._sftpSession disconnect];
  }
}
```

Please let me know if the client.disconnect() workaround works for you for now while we try to resolve this bug.

Best regards,
Josh

**Comment by ahoelzemann** [comment]
yes, it works. Thanks again!
