### ISSUE TITLE
ld: library not found for -lcrypto

### ISSUE THREAD

**Issue by LollipopKit** [jda258/flutter_ssh2#6]
I can run`flutter run` to install app on my iPhone, but when I use `flutter build ios` or Xcode archive/profile, it throw `ld: library not found for -lcrypto` in Pod GZ-NMSSH.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10864310/133918000-c91337f7-454f-479e-a092-f86c53bacc55.png">

flutter2.5
macOS 11.5.2
iOS 14.8

how can I solve it?

**Comment by jda258** [comment]
Hello,

I haven't run into this issue, but a quick Google search brought this up: https://developer.apple.com/forums/thread/88451

Are you able to build the example app?

Best regards,
Josh

**Comment by jda258** [comment]
When I've had build issues with iOS in the past, this has helped:

1. Run `flutter clean && flutter pub get` in your project directory
2. Make sure you're using the latest version of CocoaPods by running the command `sudo gem install cocoapods`
3. Run `pod deintegrate && rm Podfile.lock && pod install --repo-update` in your project's ios directory
4. Now try building

**Comment by LollipopKit** [comment]
Thanks for you reply.

I have tried the solution you gave, but it doesn't work.
`flutter build ios` throw the same error.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10864310/133927043-7cec6c86-386e-4ca3-a8fe-867f9d7a9add.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10864310/133927055-f71f825e-450b-4f45-b905-a49f16e7a909.png">

The solution on https://developer.apple.com/forums/thread/88451 also doesn't seem to work, because I use the same iOS version in main project and pod plugins.
I put the Sample App on [git](https://github.com/LollipopKit/toolbox).

Thank you so much for taking the time to help me solve the problem.

**Comment by jda258** [comment]
It looks like your build settings need some adjusting. One of the solutions at https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io should hopefully work. I'm closing this as it is unrelated to the ssh2 package.

**Comment by jda258** [comment]
I just published version 2.2.3, which excludes the arm64 architecture for the simulator. You may need to delete your Podfile.lock and run `flutter clean` before building. Hopefully this fixes your issue at the plugin level so you don't need to do overrides in your Podfile.
